### ISSUE TITLE
Option to loop the video

### ISSUE THREAD

**Issue by DL854359743057** [PaulleDemon/tkVideoPlayer#1]
Thanks for this great library!
Is there an option to loop the video infinitly?

**Comment by PaulleDemon** [comment]
Hello, once the video ends the program emits `<<Ended>>` event. You can bind this to a function and use `play` method to play again.

```py
import tkinter as tk
from tkVideoPlayer import TkinterVideo

def loop(event):
    print("Ended")
    videoplayer.play()

# def stop_video():
#     # Stop the video before destroying the window
#     videoplayer.pause()
#     videoplayer.stop()
#     root.destroy()

root = tk.Tk()

videoplayer = TkinterVideo(master=root)
videoplayer.load(r"samplevideo.mp4")
videoplayer.pack(expand=True, fill="both")

videoplayer.play() # play the video

videoplayer.bind("<<Ended>>", loop)

#root.protocol("WM_DELETE_WINDOW", stop_video)
root.mainloop()
```

Note: if you are using python IDLE to write and interpret your programs you might get the below error
```
RuntimeError: main thread is not in main loop
```
this is likely caused due to python IDLE running its own tkinter mainloop (as the IDLE is also made using tkinter ;) ). So as a temporary fix, you can try uncommenting `root.protocol("WM_DELETE_WINDOW", stop_video)`. But I would suggest using a different IDE such as vscode, pycharm etc.

Let me know if you face any problems thanks.

**Comment by PaulleDemon** [comment]
If you found this helpful let me know I'll close the issue

**Comment by PaulleDemon** [comment]
@DL854359743057 I'll be closing this in 24hrs. If you have any problem let me know, else I'll be closing this issue. Thank you.
